// <auto-generated />
using System;
using System.Collections.Generic;
using LedgerCore.Ledger.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LedgerCore.Ledger.Api.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260923115412_PolicyApprovalEvidence")]
    partial class PolicyApprovalEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LedgerCore.Ledger.Api.Persistence.JournalPolicyDecision", b =>
                {
                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contract_version");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("policy_version");

                    b.PrimitiveCollection<List<string>>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reason_codes");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("JournalId")
                        .HasName("pk_journal_policy_decisions");

                    b.HasIndex("DecisionId")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_policy_decisions_decision");

                    b.ToTable("journal_policy_decisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_policy_decisions_decision", "decision IN ('APPROVED', 'REJECTED', 'REVIEW_REQUIRED')");

                            t.HasCheckConstraint("ck_journal_policy_decisions_reasons", "(decision = 'APPROVED') = (cardinality(reason_codes) = 0)");

                            t.HasCheckConstraint("ck_journal_policy_decisions_version", "length(policy_version) BETWEEN 1 AND 128");
                        });
                });

            modelBuilder.Entity("LedgerCore.Ledger.Api.Persistence.JournalStatusTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_journal_status_transitions");

                    b.HasIndex("JournalId", "Id")
                        .HasDatabaseName("ix_journal_status_transitions_journal_id_id");

                    b.ToTable("journal_status_transitions", (string)null);
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasAlternateKey("Id", "LedgerId", "Currency")
                        .HasName("ak_accounts_id_ledger_id_currency");

                    b.HasIndex("LedgerId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_ledger_code");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_active_state", "(is_active AND deactivated_at IS NULL) OR (NOT is_active AND deactivated_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_accounts_type", "type IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE')");
                        });
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Journals.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("PostedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("posted_by");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("ReversesJournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_journal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("submitted_by");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_journals");

                    b.HasAlternateKey("Id", "LedgerId", "Currency")
                        .HasName("ak_journals_id_ledger_id_currency");

                    b.HasIndex("ReversesJournalId")
                        .IsUnique()
                        .HasDatabaseName("ux_journals_live_reversal")
                        .HasFilter("reverses_journal_id IS NOT NULL AND status <> 'REJECTED'");

                    b.HasIndex("LedgerId", "ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ux_journals_ledger_external_reference")
                        .HasFilter("external_reference IS NOT NULL");

                    b.HasIndex("LedgerId", "Status")
                        .HasDatabaseName("ix_journals_ledger_id_status");

                    b.HasIndex("ReversesJournalId", "LedgerId", "Currency")
                        .HasDatabaseName("ix_journals_reverses_journal_id_ledger_id_currency");

                    b.ToTable("journals", null, t =>
                        {
                            t.HasCheckConstraint("ck_journals_approved_fields", "(status IN ('APPROVED', 'POSTED') AND approved_at IS NOT NULL AND approved_by IS NOT NULL) OR (status NOT IN ('APPROVED', 'POSTED') AND approved_at IS NULL AND approved_by IS NULL)");

                            t.HasCheckConstraint("ck_journals_not_self_reversal", "reverses_journal_id IS NULL OR reverses_journal_id <> id");

                            t.HasCheckConstraint("ck_journals_posted_fields", "(status = 'POSTED' AND posted_at IS NOT NULL AND posted_by IS NOT NULL) OR (status <> 'POSTED' AND posted_at IS NULL AND posted_by IS NULL)");

                            t.HasCheckConstraint("ck_journals_rejected_fields", "(status = 'REJECTED' AND rejected_at IS NOT NULL AND rejected_by IS NOT NULL AND rejection_reason IS NOT NULL) OR (status <> 'REJECTED' AND rejected_at IS NULL AND rejected_by IS NULL AND rejection_reason IS NULL)");

                            t.HasCheckConstraint("ck_journals_status", "status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'POSTED')");

                            t.HasCheckConstraint("ck_journals_submitted_fields", "(status = 'DRAFT' AND submitted_at IS NULL AND submitted_by IS NULL) OR (status <> 'DRAFT' AND submitted_at IS NOT NULL AND submitted_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_journals_transaction_type", "transaction_type IN ('PAYMENT', 'TRANSFER', 'ADJUSTMENT', 'REVERSAL', 'FEE')");
                        });
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Journals.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(22,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("direction");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Memo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memo");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("JournalId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_journal_id_line_number");

                    b.HasIndex("AccountId", "LedgerId", "Currency")
                        .HasDatabaseName("ix_journal_entries_account_id_ledger_id_currency");

                    b.HasIndex("JournalId", "LedgerId", "Currency")
                        .HasDatabaseName("ix_journal_entries_journal_id_ledger_id_currency");

                    b.ToTable("journal_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_entries_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_journal_entries_direction", "direction IN ('DEBIT', 'CREDIT')");

                            t.HasCheckConstraint("ck_journal_entries_line_number", "line_number >= 1");
                        });
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Ledgers.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ledgers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_ledgers_code");

                    b.ToTable("ledgers", (string)null);
                });

            modelBuilder.Entity("LedgerCore.Ledger.Api.Persistence.JournalPolicyDecision", b =>
                {
                    b.HasOne("LedgerCore.Ledger.Domain.Journals.Journal", null)
                        .WithOne()
                        .HasForeignKey("LedgerCore.Ledger.Api.Persistence.JournalPolicyDecision", "JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_policy_decisions_journals_journal_id");
                });

            modelBuilder.Entity("LedgerCore.Ledger.Api.Persistence.JournalStatusTransition", b =>
                {
                    b.HasOne("LedgerCore.Ledger.Domain.Journals.Journal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_status_transitions_journals_journal_id");
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Accounts.Account", b =>
                {
                    b.HasOne("LedgerCore.Ledger.Domain.Ledgers.Ledger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_ledgers_ledger_id");
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Journals.Journal", b =>
                {
                    b.HasOne("LedgerCore.Ledger.Domain.Ledgers.Ledger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journals_ledgers_ledger_id");

                    b.HasOne("LedgerCore.Ledger.Domain.Journals.Journal", null)
                        .WithMany()
                        .HasForeignKey("ReversesJournalId", "LedgerId", "Currency")
                        .HasPrincipalKey("Id", "LedgerId", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journals_reversed_journal");
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Journals.JournalEntry", b =>
                {
                    b.HasOne("LedgerCore.Ledger.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "LedgerId", "Currency")
                        .HasPrincipalKey("Id", "LedgerId", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_account");

                    b.HasOne("LedgerCore.Ledger.Domain.Journals.Journal", null)
                        .WithMany("Entries")
                        .HasForeignKey("JournalId", "LedgerId", "Currency")
                        .HasPrincipalKey("Id", "LedgerId", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_journal");
                });

            modelBuilder.Entity("LedgerCore.Ledger.Domain.Journals.Journal", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
